name: anomaly workflow

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install Dependencies
              run: pip install -r anomaly_ids/requirements.txt
            
            - name: Run tests 
              run: pytest anomaly_ids/tests

    linting:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v4  
 
          - name: Setup Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install Ruff
            run: pip install ruff

          - name: Start linting
            run: ruff check --select E9,F63,F7,F82 .
